"""Update

Revision ID: d659beda276d
Revises: 44adce647800
Create Date: 2023-01-27 18:37:46.133837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd659beda276d'
down_revision = '44adce647800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_test_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key('', 'users', ['poster_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_test_user_id_user', 'users', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###
